export const TRANSLATION = {
    en: {
      title: "Star Wars Films",
      loading: "Loading...",
      error: "Error!",
      director: "Director:",
      releaseYear: "Release Year:",
      sortBy: "Sort by:",
      titleLabel: "Title",
      releaseDateLabel: "Release Date",
      noMoviesTitle: "No movies found",
      noMoviesDescription: "No movies match the applied filters.",
      previous: "Previous",
      next: "Next",
      page: "Page",
      of: "of",
      episodeId: "Episode ID",
      producers: "Producers",
      switchToGerman: "Switch to German",
      germanFlag: "/german.png",
      germanFlagAlt: "German Flag",
      all: "All"
    },
    de: {
      title: "Star Wars Filme",
      loading: "Lädt...",
      error: "Fehler!",
      director: "Regisseur:",
      releaseYear: "Erscheinungsjahr:",
      sortBy: "Sortieren nach:",
      titleLabel: "Titel",
      releaseDateLabel: "Erscheinungsdatum",
      noMoviesTitle: "Keine Filme gefunden",
      noMoviesDescription: "Keine Filme entsprechen den angewandten Filtern.",
      previous: "Vorherige",
      next: "Nächste",
      page: "Seite",
      of: "von",
      episodeId: "Episoden-ID",
      producers: "Produzenten",
      switchToEnglish: "Wechseln zu Englisch",
      ukFlag: "/uk.png",
      ukFlagAlt: "UK Flag",
      all: "Alle"
    },
  };
  